# Generated by Django 3.1.7 on 2021-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[(1, 'pending'), (2, 'pending'), (3, 'rejected'), (4, 'archived')], max_length=255, null=True),
        ),
    ]
