# Generated by Django 3.1.7 on 2021-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210304_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(blank=True, choices=[(1, 'pending'), (2, 'published'), (3, 'rejected'), (4, 'archived')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
