# Generated by Django 3.1.7 on 2021-03-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210304_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(blank=True, choices=[('pending', 1), ('published', 2), ('rejected', 3), ('archived', 4)], max_length=80, null=True),
        ),
    ]
