# Generated by Django 3.1.7 on 2021-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210304_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected'), ('archived', 'archived')], default='draft', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('astronomy', 'astronomy'), ('cosmology', 'cosmology'), ('exoplanets', 'exoplanets'), ('editorial', 'editorial')], default='astronomy', max_length=80, null=True),
        ),
    ]
