# Generated by Django 3.1.7 on 2021-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210305_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected'), ('archived', 'archived')], default='draft', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('astronomy', 'astronomy'), ('cosmology', 'cosmology'), ('exoplanets', 'exoplanets'), ('editorial', 'editorial')], default='astronomy', max_length=80),
        ),
    ]
