# Generated by Django 3.1.7 on 2021-03-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210305_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
    ]
