# Generated by Django 3.1.7 on 2021-04-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='body',
        ),
    ]
